services:
  bootmessages:
    container_name: bootmessage
    image: bootmessage:latest
    build:
      context: ../
      dockerfile: ./.containerboot/Dockerfile
    volumes:
      - .:/app
    env_file:
      - ../.config/.env
    ports:
      - "8080:8080"
    command: sleep infinity

    # docker compose -f .containerboot/docker-compose.yml down --rmi all --volumes
    # docker compose -f .containerboot/docker-compose.yml up --build -d