on:
  schedule:
    - cron: '0 7 * * MON-FRI'
  workflow_dispatch:

jobs:
  send_messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar o Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io docker-compose
      
    - name: Criar os environments
      env:
        URL:    ${{ secrets.URL }}
        TOKEN:  ${{ secrets.TOKEN }}
        NOME:   ${{ secrets.NOME }}
        NUMERO: ${{ secrets.NUMERO }}
      run: |
        mkdir .config/.env
        echo "URL=${{ secrets.URL }}" >> .config/.env
        echo "TOKEN=${{ secrets.TOKEN }}" >> .config/.env
        echo "NOME=${{ secrets.NOME }}" >> .config/.env
        echo "NUMERO=${{ secrets.NUMERO }}" >> .config/.env

    - name: Iniciar Container
      run: |
        docker-compose -f .containerbot/docker-compose.yml up --build -d
    
    - name: Executar script de mensagens
      run: |
        $result=docker exec -it botmessage python main/main.py
        echo "result: $result"
        if [ "$result" == "OK" ]; then
          echo "Mensagem enviada com sucesso!"
        else
          echo "Erro ao enviar mensagem."
        fi