on:
  schedule:
    - cron: '0 7 * * MON-FRI'
  workflow_dispatch:

jobs:
  send_messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Docker do repositório oficial
      run: |
        sudo apt-get update
        sudo apt-get install -y ca-certificates curl gnupg
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      
    - name: Criar os environments
      run: |
        mkdir -p .config
        {
          echo "URLINTEGRACAO=${{ secrets.URL }}"
          echo "TOKEN=${{ secrets.TOKEN }}"
          echo "NOMEENVIO=${{ secrets.NOME }}"
          echo "NUMEROENVIO=${{ secrets.NUMERO }}"
        } > .config/.env

        $test=cat .config/.env
        echo "FILE ENVIRONMENT: $test"

    # - name: Iniciar Container
    #   run: |
    #     docker compose -f .containerbot/docker-compose.yml up --build -d
    
    # - name: Executar script de mensagens
    #   run: |
    #     docker exec botmessage python main/main.py > result.log
    #     if grep -q "Erro" result.log; then
    #       echo "Erro ao enviar mensagens"
    #       exit 1
    #     else
    #       echo "Mensagens enviadas com sucesso"
    #     fi