on:
  schedule:
    - cron: '0 7 * * MON-FRI'
  workflow_dispatch:

jobs:
  send_messages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: instalar docker
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose -y

    - name: Iniciar Container
      run: |
        docker-compose -f .containerbot/docker-compose.yml up --build -d

    - name: Setar variaveis de ambiente no container
      env:
        NOME: ${{ secrets.NOME }}
        NUMEROENVIO: ${{ secrets.NUMEROENVIO }}
        TOKEN: ${{ secrets.TOKEN }}
        URL: ${{ secrets.URL }}

      run: |
        docker exec -it botmessage bash -c "echo 'NOME=$NOME' >> /container/.config/.env"
        docker exec -it botmessage bash -c "echo 'NUMEROENVIO=$NUMEROENVIO' >> /container/.config/.env"
        docker exec -it botmessage bash -c "echo 'TOKEN=$TOKEN' >> /container/.config/.env"
        docker exec -it botmessage bash -c "echo 'URL=$URL' >> /container/.config/.env"

    - name: Executar Script
      run: |
        $result = docker exec -it botmessage python main/main.py
        echo "Resultado do script: $result"
        if ($result -eq 0) {
          echo "Script executado com sucesso."
        } else {
          echo "Erro ao executar o script."
          exit 1
        }